name: Test library-backend

on:
  push:
    branches: [ main, master ] # Раскомментируем, чтобы тесты шли автоматически при каждом push
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Поднимаем изолированную базу данных MongoDB внутри контейнера GitHub
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install library-backend dependencies
        working-directory: library-backend
        run: npm ci

      - name: Install test dependencies
        working-directory: tests-chapter4
        run: npm ci

      - name: Run tests
        working-directory: tests-chapter4
        run: npm test
        env:
          # Передаем тестовые переменные окружения прямо в рантайм тестов
          MONGODB_URI: mongodb://localhost:27017/testGraphqlLibrary
          JWT_SECRET: MARINA_SUPER_SECRET_KEY_123
